---
lang: "en"
title: "Bookdown testing"
subtitle: "subtitle here"
author: ["Jack Dougherty", "Ilya Ilyankou"]
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
documentclass: book

url: 'http\://handsondataviz.github.io/bookdown-testing'
github-repo: handsondataviz/bookdown-testing
description: 'This is a test book'

output:
  bookdown::gitbook:
    dev: svglite
    css: css/style.css
    includes:
      in_header: [custom-scripts.html]
    toc_depth: 2
    split_by: section
    number_sections: true
    split_bib: true
    config:
      toc:
        scroll_highlight: yes
        collapse: section
        before: |
            <li><strong><a href="./">Bookdown testing</a></strong></li>
        after: |
            <li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>
      download: [pdf]
      view: https://github.com/handsondataviz/bookdown-testing/edit/master/%s
      search: yes
      sharing:
        facebook: yes
        github: yes
        twitter: yes

  bookdown::pdf_book:
    toc_depth: 2
    number_sections: true

  bookdown::word_document2:
    default

  bookdown::markdown_document2:
    default

---
# Preface {-}
<!-- R global options: R chunk images display without code (no echo); show PDF image over JPG/PNG when available -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.graphics.auto_pdf = TRUE)
```

This test book was last updated on `r format (Sys.Date(), '%d %b %Y')`

Insert additional preface items below (acknowledgements, etc.), with non-numbering symbols `{-}` to ensure that the preface is not numbered, and the first chapter is properly numbered as chapter one.

Reminder: Bookdown does not auto-number figures in the `index.Rmd` file, which serves as a "preface" file.

### Acknowledgements {-}

Cupcake ipsum dolor sit amet jelly beans wafer pudding. Bear claw lemon drops carrot cake pie wafer chocolate jelly cheesecake. Chocolate cheesecake chocolate bar sugar plum sweet dessert tart. Tootsie roll bear claw chocolate bar wafer powder sugar plum tiramisu bear claw gummies. Tart macaroon pastry lemon drops candy tootsie roll chocolate candy canes lollipop. Pudding fruitcake bear claw sweet cake cupcake. Chupa chups pudding candy canes chupa chups powder jujubes chocolate cake cotton candy jelly.

## Copyright and Open-Access {-}

Cupcake ipsum dolor sit amet jelly beans wafer pudding. Bear claw lemon drops carrot cake pie wafer chocolate jelly cheesecake. Chocolate cheesecake chocolate bar sugar plum sweet dessert tart. Tootsie roll bear claw chocolate bar wafer powder sugar plum tiramisu bear claw gummies. Tart macaroon pastry lemon drops candy tootsie roll chocolate candy canes lollipop. Pudding fruitcake bear claw sweet cake cupcake. Chupa chups pudding candy canes chupa chups powder jujubes chocolate cake cotton candy jelly.
